# filename: ex264.rq

PREFIX dbr: <http://dbpedia.org/resource/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?o ?decimalTest
WHERE 
{
  ?s ?p ?o . 
  BIND (STRDT(str(?o),xsd:decimal) as ?decimalTest)
}

