# filename: ex415.rq

PREFIX ab: <http://learningsparql.com/ns/addressbook#> 

SELECT ?firstName ?lastName 
WHERE 
{
  ?person a ab:Musician ;
          ab:firstName ?firstName ;
          ab:lastName ?lastName . 
}

