# filename: ex459.rq

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX gr:   <http://purl.org/goodrelations/v1#>

SELECT * 
WHERE 
{
   ?bf a gr:BusinessFunction ;
       rdfs:label ?label . 
   OPTIONAL { ?bf rdfs:comment ?comment }
}

