#filename: ex537.rq

PREFIX ab:   <http://learningsparql.com/ns/addressbook#> 
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 

SELECT ?property ?propName
WHERE 
{ 
  ?property rdfs:domain ab:Person ;
            rdfs:label ?propName .  
}

