# filename: ex055.rq

PREFIX ab: <http://learningsparql.com/ns/addressbook#> 

SELECT ?first ?last ?workTel
WHERE
{
  ?s ab:firstName ?first ;
     ab:lastName ?last ; 
     ab:workTel ?workTel .
}

