# filename: ex276.rq

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 

SELECT ?strippedLabel
WHERE { 
  ?s rdfs:label ?label .
  FILTER ( langMatches(lang(?label),"en" ))
  BIND (str(?label) AS ?strippedLabel)
}

