# filename: ex541.rq

PREFIX e: <http://learningsparql.com/ns/expenses#> 

SELECT UCASE(SUBSTR(?description,1,3))  ?amount

WHERE
{
  ?meal e:description ?description ;
        e:amount ?amount . 
}

